titleAndCommits: true

scopes:
  - deps
  - gha
  - export
  - version
  - release-note

types:
  - feat
  - improvement
  - fix
  - perf
  - docs
  - build
  - ci
  - refactor
  - revert
  - test
  - chore

allowMergeCommits: false
