name: Build project

on:
  push:
    branches: [ master, develop ]
    tags-ignore:
      - "*"
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Restore .NET Core tools
        run: dotnet tool restore
      - name: Build
        run: dotnet cake
