name: Build project

on:
  push:
    branches: [master, develop, virtual-image-updates]
    tags-ignore:
      - "*"
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, ubuntu-20.04, windows-2019]
    env:
      NUGET_SOURCE: https://f.feedz.io/wormiecorp/packages/nuget/index.json
      NUGET_API_KEY: ${{ secrets.FEEDZ_API_KEY }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v2.1.0
        with:
          dotnet-version: |
            3.1.x
            5.0.x
            6.0.x
            7.0.x
      - name: Build
        run: ./build.ps1
        shell: pwsh
      - name: Upload Coverage Report
        if: always()
        uses: codecov/codecov-action@v3.1.4
        with:
          directory: ./.artifacts/coverage/tests
