name: Build project

on:
  push:
    branches: [master, develop]
    tags-ignore:
      - "*"
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-18.04, windows-2019]
    env:
      NUGET_SOURCE: https://f.feedz.io/wormiecorp/packages/nuget/index.json
      NUGET_API_KEY: ${{ secrets.FEEDZ_API_KEY }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        run: ./build.ps1
        shell: pwsh
