name: Build Release project

on:
  push:
    branches:
      - 'virtual-image-updates'
      - "!*"
      - "!*/*"
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      NUGET_SOURCE: https://api.nuget.org/v3/index.json
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.DRAFT_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v2.1.0
        with:
          dotnet-version: |
            3.1.x
            5.0.x
            6.0.x
            7.0.x
      - name: Restore .NET Core tools
        run: dotnet tool restore
      - name: Build
        run: ./build.sh --target=Publish-Release
