name: Build Release project

on:
  push:
    branches:
      - "!*"
      - "!*/*"
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      NUGET_SOURCE: https://api.nuget.org/v3/index.json
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.DRAFT_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Restore .NET Core tools
        run: dotnet tool restore
      - name: Build
        run: ./build.sh --target=Publish-Release
