name: TOC Generator

on: [push]

jobs:
  toc:
    name: TOC Generator
    runs-on: ubuntu-latest

    steps:
      - uses: technote-space/toc-generator@v3.1.2
        with:
          COMMIT_MESSAGE: "docs: Update TOC"
          TARGET_PATHS: "README.md,CONTRIBUTING.md"
          TOC_TITLE: "## Table of Contents"
          PR_TITLE: "docs: Update TOC (${PR_MERGE_REF})"
          GITHUB_TOKEN: ${{ secrets.DRAFT_TOKEN }}
